language: node_js
node_js: node

cache:
    directories:
        - "node_modules"

before_install: npm install -g greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script: npm run dev

after_script: greenkeeper-lockfile-upload

notifications:
    email: false
