language: node_js
node_js: lts/*

install: npm ci

script: npm run build

after_success: cd dist && zip -r ../kalendario.zip . && cd ..

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: kalendario.zip
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
